language: java

os:
  - osx

sudo: required

services:
  - docker

jdk:
  - oraclejdk8

install:
  - nvm install 8
  - nvm use 8
  - node --version
  - npm -g install mocha
  - which node
  - which mocha

script:
  - ./gradlew -s -i check
  - ./gradlew_win -s -i check
  - ./gradlew_linux -s -i check

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan
    
